const productss = [
    {id: 0, title: "iPhone 7 Plus", price: 2500, type: "Çocuk", counter:450, dealerid: 0},
    {id: 1, title: "Samsung Galaxy S10", price: 3900, type: "Çocuk", counter:275,dealerid: 1 }, 
    {id: 2, title: "HP Yazıcı", price: 500, type: "Çocuk", counter:78,dealerid: 0 }, 
    {id: 3, title: "Razer Klavye", price: 1000, type: "Çocuk", counter:154,dealerid: 0 },
    {id: 4, title: "Jordan Basketbol Topu", price: 150, type: "Kültür", counter:450, dealerid: 1},
    {id: 5, title: "Halter Seti", price: 5000, type: "Kültür", counter:48,dealerid: 0},
    {id: 6, title: "Beyzbol Sopası", price: 400, type: "Kültür", counter:32,dealerid: 1},
    {id: 7, title: "Nike Futbol Topu", price: 200, type: "Kültür", counter: 220,dealerid: 0},
    {id: 8, title: "Tofaş Şahin", price: 60000, type: "Tarih", counter: 155,dealerid: 1},     
    {id: 9, title: "Volkswagen Passat", price: 500000, type: "Tarih", counter:200, dealerid: 0},
    {id: 10, title: "Seat Leon", price: 300000, type: "Tarih", counter: 304,dealerid: 1},
    {id: 11, title: "Porsche Cayenne", price: 1500000, type: "Tarih", counter: 150,dealerid: 0},
    {id: 12, title: "Kanepe Seti", price: 15000, type: "Edebiyat", counter: 53,dealerid: 1},
    {id: 13, title: "Ahşap Dolap", price: 2000, type: "Edebiyat", counter: 97,dealerid: 0},
    {id: 14, title: "Yatak", price: 3000, type: "Edebiyat", counter: 184,dealerid: 1},
    {id: 15, title: "Antika Koltuk", price: 20000, type: "Edebiyat", counter: 297,dealerid: 0},
    {id: 16, title: "Rayban Gözlük", price: 700, type: "Felsefe", counter: 163,dealerid: 1},
    {id: 17, title: "Takım Elbise", price: 1300, type: "Felsefe", counter: 281,dealerid: 0},
    {id: 18, title: "Siyah Çizme", price: 700, type: "Felsefe", counter: 112,dealerid: 1},
    {id: 19, title: "Lacivert Mont", price: 400, type: "Felsefe", counter: 260,dealerid: 0},
    {id: 20, title: "Pırlanta Yüzük", price: 35000, type: "Psikoloji", counter: 210,dealerid: 1},
    {id: 21, title: "Rolex Saat", price: 85000, type: "Psikoloji", counter:110,dealerid: 0},
    {id: 22, title: "Küpe", price: 200, type: "Psikoloji", counter:192,dealerid: 1},
    {id: 23, title: "Altın Bilezik", price: 7000, type: "Psikoloji", counter:250,dealerid: 0},
    {id: 24, title: "Harry Potter Serisi", price: 500, type: "Kişisel Gelişim", counter:390,dealerid: 1},
    {id: 25, title: "Peter Pan", price: 50, type: "Kişisel Gelişim", counter: 50,dealerid: 0},
    {id: 26, title: "Küçük Kara Balık", price: 30, type: "Kişisel Gelişim", counter: 84,dealerid: 1},
    {id: 27, title: "Kuyucaklı Yusuf", price: 70, type: "Kişisel Gelişim", counter: 116,dealerid: 0},
    {id: 28, title: "İsviçre Çakısı", price: 210, type: "Hukuk", counter: 290,dealerid: 1},
    {id: 29, title: "Casio Org", price: 1000, type: "Hukuk", counter: 375,dealerid: 0},
    {id: 30, title: "Kum Saati", price: 50, type: "Hukuk", counter:422,dealerid: 1},
    {id: 31, title: "Kahve",price: 400, type: "Hukuk", counter:450, dealerid:1},
    {id: 32, title: "Adalet Sistemleri",price: 50, type: "Hukuk", counter:1200, dealerid:3}];
export default productss;